// src/react/ExampleFrame.tsx
import * as React from 'react';

export interface ExampleFrameProps {
    title: string;
    subtitle: string;
}

export class ExampleFrame extends React.Component<ExampleFrameProps> {

    public render() {
        return <div className="container mt-5">
            <div className="card">
                <div className="card-body">

                    {/* FRAMEWORK ICON */}
                    <img src={"/res/react-icon-small.png"} className="float-right" width="30" height="30" title="Using React" alt="Using React" />

                    {/* TITLE AND STUFF */}
                    <h2 className="card-title mb-3">redux-app-examples</h2>
                    <h6 className="card-subtitle text-muted mb-2">
                        examples of <a href="https://github.com/alonrbar/redux-app">redux-app</a> together with your favorite client side framework
                            </h6>
                    <a href="/"><i><small>back to main menu</small></i></a>
                    <br /><br />
                    <h4><i>{this.props.title}</i></h4>
                    <h4><small className="text-muted">{this.props.subtitle}</small></h4>

                    {/* EXAMPLE CONTENT GOES HERE */}
                    {this.props.children}

                </div>
            </div>
        </div>;
    }
}

// src/angular/example-frame.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'example-frame',
    templateUrl: './example-frame.component.html'
  })
export class ExampleFrameComponent {
    @Input() public title: string;
    @Input() public subtitle: string;
}
<div>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">

                <!-- TITLE AND STUFF -->
                <h2 class="card-title mb-3">redux-app-examples</h2>
                <h6 class="card-subtitle text-muted mb-2">
                    examples of <a href="https://github.com/alonrbar/redux-app">redux-app</a> together with your favourite client side framework
                </h6>
                <a href="/"><i><small>back to main menu</small></i></a>
                <br><br>
                <h4><i>{{title}}</i></h4>
                <h4><small class="text-muted">{{subtitle}}</small></h4>

                <!-- EXAMPLE CONTENT GOES HERE -->
                <ng-content></ng-content>

            </div>
        </div>
    </div>
</div>
