// src/react/withId/view/Counter.tsx
import * as React from 'react';
import { CounterState } from '../state';

export const Counter: React.SFC<CounterState & { title: string }> = (props) => (
    <div className="card">
        <div className="card-body">
            {props.title && <h4 className="card-title mb-4">{props.title}</h4>}
            <h3>{props.value}</h3>
            <button onClick={() => props.increment()}>Increment</button>
        </div>
    </div>
);

// src/angular/counters/view/counter.component.ts
import { Counter } from "../viewModel/counter";
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-counter',
    templateUrl: './counter.component.html'
  })
export class CounterComponent {
    @Input() public vm: Counter;
}
<div>
    <div class="card">
        <div class="card-body">
            <h3>{{vm.value}}</h3>
            <button (click)="vm.increment(vm.id)">Increment</button>
        </div>
    </div>
</div>
