// src/react/todo/view/VisibleTodoList.tsx
import * as React from 'react';
import { connect } from 'redux-app';
import { autoSync } from '../../autoSync';
import { App, VisibleTodoListState } from '../state';
import { Todo } from './Todo';

const VisibleTodoList: React.SFC<VisibleTodoListState> = (props) => (
    <ul>
        {props.visibleTodos.map(todo => (
            <Todo key={todo.id} onClick={() => props.toggleTodo(todo.id)} todo={todo}></Todo>
        ))}
    </ul>
);

const connected = autoSync(VisibleTodoListState)(VisibleTodoList);
export { connected as VisibleTodoList };

// src/angular/todo/view/visible-todo-list.component.ts
import { ChangeDetectorRef, Component } from '@angular/core';
import { connect } from 'redux-app';
import { VisibleTodoList } from '../view-model';

@Component({
    selector: 'visible-todo-list',
    templateUrl: './visible-todo-list.component.html'
})
export class VisibleTodoListComponent {

    @connect
    public vm: VisibleTodoList;
}
<div>
    <ul>
        <todo *ngFor="let todo of vm.visibleTodos" (onTodoClick)="vm.toggleTodo($event)" [todo]="todo"></todo>
    </ul>
</div>
