// src/angular/gladiators/view/gladiatorThumbnail/gladiatorThumbnail.component.ts
import { Component, Input } from '@angular/core';
import '../../assets/style/gladiator-banner.css';
import { Banner, Gladiator } from '../../model';
import './gladiatorThumbnail.component.css';

@Component({
    selector: 'gladiator-thumbnail',    
    templateUrl: './gladiatorThumbnail.component.html'
})
export class GladiatorThumbnailComponent {

    public readonly credits = Banner.credits;

    @Input() public gladiator: Gladiator;
}
<div class="card gladiator-thumbnail" [title]="gladiator.name">

    <!-- banner -->
    <img class="card-img bg-light gladiator-banner" [ngClass]="gladiator.banner">

    <div class="card-img-overlay">
        <div class="card-bottom">

            <!-- name -->
            <span class="float-left gladiator-name">{{gladiator.name}}</span>

            <!-- wins -->
            <span class="float-right badge badge-warning">{{gladiator.wins}}</span>
        </div>
    </div>
</div>

// src/react/gladiators/view/gladiatorThumbnail.tsx
import * as React from 'react';
import '../assets/style/gladiator-banner.css';
import { Banner, Gladiator } from '../model';
import './gladiatorThumbnail.css';

export interface GladiatorThumbnailProps {
    gladiator: Gladiator;
    onClick: () => void;
}

export const GladiatorThumbnail: React.SFC<GladiatorThumbnailProps> = (props) => (

    <div className="card gladiator-thumbnail" title={props.gladiator.name} onClick={props.onClick}>

        {/*  banner */}
        <img className={"card-img bg-light gladiator-banner " + props.gladiator.banner} />

        <div className="card-img-overlay">
            <div className="card-bottom">

                {/* name */}
                <span className="float-left gladiator-name">{props.gladiator.name}</span>

                {/* wins */}
                <span className="float-right badge badge-warning">{props.gladiator.wins}</span>
            </div>
        </div>
    </div>
);
