// src/angular/gladiators/view/gladiatorPage/gladiatorPage.component.ts
import { Component } from '@angular/core';
import { connect } from 'redux-app';
import { GladiatorPage } from '../../viewModel';
var debounce = require('lodash.debounce');

@Component({
  selector: 'gladiator-page',
  templateUrl: './gladiatorPage.component.html'
})
export class GladiatorPageComponent {

  public nameChanged = debounce((name: string) => {
    // https://stackoverflow.com/a/42845938/999461
    this.vm.setName(name);
  }, 300);

  @connect
  public vm: GladiatorPage;

  constructor() {
    this.vm.reset();
  }
}

<div class="page">

    <!-- back button -->
    <a href="javascript:void(0)" (click)="vm.goBack()" class="float-right">Back</a>

    <div class="row">

        <!-- profile preview -->
        <div class="col-12 col-xl-3" style="min-width: 20em">
            <gladiator-profile [gladiator]="vm.tempGladiator.value"></gladiator-profile>
        </div>

        <!-- edit controls -->
        <div class="col-12 col-xl-8">
            <form class="mt-5">

                <!-- name -->
                <div class="form-group">
                    <label for="gladiatorName">Gladiator Name</label>
                    <input type="text" [ngModel]="vm.tempGladiator.value.name" (ngModelChange)="nameChanged($event)" class="form-control" name="gladiatorName"
                        placeholder="Enter name">
                </div>

                <!-- banner -->
                <div class="form-row">
                    <label class="col-3 col-form-label">Banner:</label>
                    <div class="btn-group col-9">
                        <button class="btn btn-secondary" (click)="vm.prevBanner()">&lt; Prev</button>
                        <button class="btn btn-secondary" (click)="vm.nextBanner()">Next &gt;</button>
                    </div>
                </div>

                <br>

                <!-- control buttons -->
                <div class="form-row">
                    <button class="btn btn-success m-1" (click)="vm.save()">Save</button>
                    <button class="btn btn-light m-1" (click)="vm.reset()">Cancel</button>
                </div>

                <br>
                <br>

                <!-- saved message -->
                <div class="alert alert-success alert-dismissible fade" [class.show]="vm.showStatus">
                    Gladiator Saved
                    <button class="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

// src/react/gladiators/view/gladiatorPage.tsx
import * as React from 'react';
import { connect } from 'redux-app';
import { autoSync } from '../../autoSync';
import { GladiatorPageState } from '../state';
import { GladiatorProfile } from './gladiatorProfile';
var debounce = require('lodash.debounce');

@autoSync(GladiatorPageState)
export class GladiatorPage extends React.Component {

  public nameChanged = debounce((name: string) => {
    // https://stackoverflow.com/a/42845938/999461
    this.vm.setName(name);
  }, 300);

  @connect
  public vm: GladiatorPageState;

  public componentWillMount() {
    this.vm.reset();
  }

  public render() {
    return (
      <div className="page">

        {/* back button */}
        <a href="javascript:void(0)" onClick={() => this.vm.goBack()} className="float-right">Back</a>

        <div className="row">

          {/* profile preview */}
          <div className="col-12 col-xl-3" style={{ minWidth: '20em' }}>
            <GladiatorProfile gladiator={this.vm.tempGladiator.value}></GladiatorProfile>
          </div>

          {/* edit controls */}
          <div className="col-12 col-xl-8">
            <form className="mt-5">

              {/* name */}
              <div className="form-group">
                <label htmlFor="gladiatorName">Gladiator Name</label>
                <input type="text" value={this.vm.tempGladiator.value.name} onChange={e => this.nameChanged(e.target.value)} className="form-control" name="gladiatorName"
                  placeholder="Enter name" />
              </div>

              {/* banner */}
              <div className="form-row">
                <label className="col-3 col-form-label">Banner:</label>
                <div className="btn-group col-9">
                  <button className="btn btn-secondary" onClick={() => this.vm.prevBanner()}>&lt; Prev</button>
                  <button className="btn btn-secondary" onClick={() => this.vm.nextBanner()}>Next &gt;</button>
                </div>
              </div>

              <br />

              {/* control buttons */}
              <div className="form-row">
                <button className="btn btn-success m-1" onClick={() => this.vm.save()}>Save</button>
                <button className="btn btn-light m-1" onClick={() => this.vm.reset()}>Cancel</button>
                <button className="btn btn-danger m-1" onClick={() => this.vm.delete()}>Delete</button>
              </div>

              <br />
              <br />

              {/* saved message */}
              <div className={"alert alert-success alert-dismissible fade" + (this.vm.showStatus ? 'show' : '')}>
                Gladiator Saved
                      <button className="close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }
}
