// src/angular/gladiators/view/mainPage/mainPage.component.ts
import { Component } from '@angular/core';
import { connect } from 'redux-app';
import { MainPage } from '../../viewModel';
import './mainPage.component.css';

@Component({
  selector: 'main-page',
  templateUrl: './mainPage.component.html'
})
export class MainPageComponent {

  @connect
  public vm: MainPage;
}

<div class="page">
    <div class="row">

        <!-- top fighters list -->
        <div class="col-2 text-center" style="overflow: hidden">
            <h5>Top Fighters</h5>
            <div class="list-group">
                <gladiator-thumbnail *ngFor="let gladiator of vm.topGladiators" [gladiator]="gladiator" (click)="vm.goToGladiatorPage(gladiator)"
                    class="m-2">
                </gladiator-thumbnail>
            </div>
        </div>

        <div class="col-10 page">

            <!-- buttons -->
            <div class="row mb-2" style="height: 8%">
                <div class="col d-flex justify-content-end">
                    <button class="btn btn-info" (click)="vm.newGladiator()">New Gladiator</button>
                </div>
            </div>
            <div class="row" style="height: 8%">
                <div class="col d-flex justify-content-end">
                    <button class="btn btn-info" (click)="vm.generateGladiators()">Generate 5 Gladiators</button>
                </div>
            </div>

            <!-- enter the arena -->
            <div class="row" style="height: 64%">
                <img src="../../assets/img/coliseum.png" class="coliseum" (click)="vm.toTheArena()" title="Enter the arena">
            </div>

            <!-- all gladiators list -->
            <div class="row" style="height: 20%">
                <div class="gladiators-list-container">
                    <ul class="list-inline gladiators-list mb-0">
                        <li *ngFor="let gladiator of vm.gladiatorsList.items" class="list-inline-item" (click)="vm.goToGladiatorPage(gladiator)">{{gladiator.name}}</li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>

// src/react/gladiators/view/mainPage.tsx
import * as React from 'react';
import { connect } from 'redux-app';
import { MainPageState } from '../state';
import './mainPage.css';
import { GladiatorThumbnail } from './gladiatorThumbnail';

export class MainPage extends React.Component {

    @connect
    public st: MainPageState;

    public render() {
        return (
            <div className="row">

                {/* top fighters list */}
                {this.st.topGladiators.length > 0 &&
                    <div className="col-2 text-center" style={{ overflow: 'hidden' }}>
                        <h5>Top Fighters</h5>
                        <div className="list-group">
                            {this.st.topGladiators.map(gladiator =>
                                <div key={gladiator.id} className="m-2">
                                    <GladiatorThumbnail gladiator={gladiator} onClick={() => this.st.goToGladiatorPage(gladiator)}>
                                    </GladiatorThumbnail>
                                </div>
                            )}
                        </div>
                    </div>}
                {!this.st.topGladiators.length && <div className="col-2"></div>}

                <div className="col-10 page">

                    {/* buttons */}
                    <div className="row mb-2" style={{ height: '8%' }}>
                        <div className="col d-flex justify-content-end">
                            <button className="btn btn-info" onClick={() => this.st.newGladiator()}>New Gladiator</button>
                        </div>
                    </div>
                    <div className="row" style={{ height: '8%' }}>
                        <div className="col d-flex justify-content-end">
                            <button className="btn btn-info" onClick={() => this.st.generateGladiators()}>Generate 5 Gladiators</button>
                        </div>
                    </div>

                    {/* enter the arena */}
                    <div className="row" style={{ height: '64%' }}>
                        <img src={require("../assets/img/coliseum.png")} className="coliseum" onClick={() => this.st.toTheArena()} title="Enter the arena" />
                    </div>

                    {/* all gladiators list */}
                    <div className="row" style={{ height: '20%' }}>
                        <div className="gladiators-list-container">
                            <ul className="list-inline gladiators-list mb-0">
                                {this.st.gladiatorsList.items.map(gladiator =>
                                    <li key={gladiator.id} className="list-inline-item" onClick={() => this.st.goToGladiatorPage(gladiator)}>{gladiator.name}</li>)
                                }
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        );
    }
}
