// src/react/todo/view/App.tsx
import * as React from 'react';
import { connect } from 'redux-app';
import { ExampleFrame } from '../../ExampleFrame';
import { App } from '../state';
import { AddTodoView } from './AddTodo';
import { Footer } from './Footer';
import { VisibleTodoList } from './VisibleTodoList';

export default class AppView extends React.Component {

    @connect
    public app: App;

    public render() {
        return <ExampleFrame title={this.app.title} subtitle={this.app.subtitle}>
            <div className="card mt-5 w-50">
                <div className="card-body">
                    <AddTodoView addTodo={txt => this.app.todoList.addTodo(txt)} />
                    <br />
                    <VisibleTodoList />
                    <Footer />
                </div>
            </div>
        </ExampleFrame>;
    }
}

// src/angular/todo/view/app/app.component.ts
import { Component } from '@angular/core';
import { connect, ReduxApp } from 'redux-app';
import { devToolsEnhancer } from 'redux-devtools-extension';
import { App } from '../../viewModel';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html'
})
export class AppComponent {

    public app = new ReduxApp(new App(), devToolsEnhancer(undefined));
}
<div>
    <example-frame [title]="app.root.title" [subtitle]="app.root.subtitle">

        <div class="card mt-5 w-50">
            <div class="card-body">
                <add-todo (onAddTodo)="app.root.todoList.addTodo($event)"></add-todo>
                <br>
                <visible-todo-list></visible-todo-list>
                <app-footer></app-footer>
            </div>
        </div>

    </example-frame>
</div>
