// src/react/gladiators/view/app.tsx
import { customElement } from 'aurelia-framework';
import * as React from 'react';
import { connect, LogLevel, ReduxApp } from 'redux-app';
import { devToolsEnhancer } from 'redux-devtools-extension';
import { autoSync } from '../../autoSync';
import { ExampleFrame } from '../../ExampleFrame';
import { GladiatorsAppState, Route } from '../state';
import './app.css';
import { MainPage } from './mainPage';

@autoSync(GladiatorsAppState)
export class App extends React.Component {

  public Route = Route;

  @connect
  public vm: GladiatorsAppState;

  public render() {
    return (
      <ExampleFrame title="Gladiators" subtitle="A real world application">
        <div className="card mt-5 w-100 p-3">

          {/* our primitive router */}
          {this.vm.router.currentRoute === Route.MainPage && <MainPage />}
          {/* <gladiator-page if.bind="vm.router.currentRoute === Route.GladiatorPage"></gladiator-page>
          <arena-page if.bind="vm.router.currentRoute === Route.ArenaPage"></arena-page> */}

        </div>
      </ExampleFrame>
    );
  }
}

// src/angular/gladiators/view/app.component.ts
import { Component } from '@angular/core';
import { LogLevel, ReduxApp } from 'redux-app';
import { devToolsEnhancer } from 'redux-devtools-extension';
import { GladiatorsApp, Route } from '../viewModel';
import './app.component.css';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  public Route = Route;

  public vm: GladiatorsApp;

  constructor() {
    ReduxApp.options.logLevel = LogLevel.Debug;
    const app = new ReduxApp(new GladiatorsApp(), devToolsEnhancer(undefined));
    this.vm = app.root;
  }
}
<div>

    <example-frame [title]="'Gladiators'" subtitle="A real world application">

        <div class="card mt-5 w-100 p-3">

            <!-- our primitve router -->
            <div [ngSwitch]="vm.router.currentRoute">
                <main-page *ngSwitchCase="Route.MainPage"></main-page>
                <gladiator-page *ngSwitchCase="Route.GladiatorPage"></gladiator-page>
                <arena-page *ngSwitchCase="Route.ArenaPage"></arena-page>
            </div>
            
        </div>

    </example-frame>
</div>
